// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgGXFZH0DdgLqMxMdXl4ZAC874LVEpBYU',
    appId: '1:761841649850:web:4c86163688629df04c9a83',
    messagingSenderId: '761841649850',
    projectId: 'palawa-services',
    authDomain: 'palawa-services.firebaseapp.com',
    storageBucket: 'palawa-services.firebasestorage.app',
    measurementId: 'G-1EBKD0QNMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS0gUa25G18KEb4fgDszIb7xQesBjMENc',
    appId: '1:761841649850:android:d5d64e436328acc64c9a83',
    messagingSenderId: '761841649850',
    projectId: 'palawa-services',
    storageBucket: 'palawa-services.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxO-mAln9feuE1GHRxxF65yo1CVI5VhYM',
    appId: '1:761841649850:ios:a0ac003afb0d2bec4c9a83',
    messagingSenderId: '761841649850',
    projectId: 'palawa-services',
    storageBucket: 'palawa-services.firebasestorage.app',
    iosBundleId: 'com.example.palawaServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxO-mAln9feuE1GHRxxF65yo1CVI5VhYM',
    appId: '1:761841649850:ios:a0ac003afb0d2bec4c9a83',
    messagingSenderId: '761841649850',
    projectId: 'palawa-services',
    storageBucket: 'palawa-services.firebasestorage.app',
    iosBundleId: 'com.example.palawaServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgGXFZH0DdgLqMxMdXl4ZAC874LVEpBYU',
    appId: '1:761841649850:web:e045de87d054eeb24c9a83',
    messagingSenderId: '761841649850',
    projectId: 'palawa-services',
    authDomain: 'palawa-services.firebaseapp.com',
    storageBucket: 'palawa-services.firebasestorage.app',
    measurementId: 'G-R89V8QS9XZ',
  );
}
